services:
  zunkiree-dev:
    build: .
    container_name: zunkiree-dev
    restart: unless-stopped
    networks:
      - hosting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zunkiree-dev.rule=Host(`dev-web.zunkireelabs.com`)"
      - "traefik.http.routers.zunkiree-dev.entrypoints=websecure"
      - "traefik.http.routers.zunkiree-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.zunkiree-dev.loadbalancer.server.port=80"

networks:
  hosting:
    external: true
